from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Callable


class PluginGenerator:
    def __init__(self, plugins_root: str | Path) -> None:
        self.plugins_root = Path(plugins_root).resolve()
        self.plugins_root.mkdir(parents=True, exist_ok=True)

    def generate_plugin(
        self,
        request: str,
        auto_confirm: bool = False,
        confirm_callback: Callable[[str], bool] | None = None,
    ) -> dict[str, Any]:
        spec = self.preview_plugin(request)
        prompt = f"Create plugin scaffold '{spec['plugin_name']}' in {spec['path']}?"
        if not auto_confirm:
            confirmed = confirm_callback(prompt) if confirm_callback else False
            if not confirmed:
                return {"created": False, "message": "Plugin generation cancelled.", "spec": spec}

        plugin_dir = Path(spec["path"])
        plugin_dir.mkdir(parents=True, exist_ok=True)
        (plugin_dir / "plugin.py").write_text(spec["plugin_py"], encoding="utf-8")
        (plugin_dir / "README.md").write_text(spec["readme"], encoding="utf-8")
        return {"created": True, "message": "Plugin scaffold generated.", "spec": spec}

    def preview_plugin(self, request: str) -> dict[str, Any]:
        cleaned = request.strip()
        if not cleaned:
            raise ValueError("Plugin request cannot be empty.")
        slug = self._slugify(cleaned)
        if not slug.endswith("_plugin"):
            slug = f"{slug}_plugin"
        title = self._title_from_slug(slug)
        tool_name = self._tool_name(slug)
        category = self._category(cleaned)
        description = f"Generated BOSS plugin for: {cleaned}"
        plugin_dir = self.plugins_root / slug
        return {
            "plugin_name": title,
            "tool_name": tool_name,
            "category": category,
            "path": str(plugin_dir),
            "plugin_py": self._render_plugin(slug, title, description, tool_name, category, cleaned),
            "readme": self._render_readme(title, cleaned, tool_name),
        }

    def generated_plugins(self, limit: int = 50) -> list[dict[str, Any]]:
        items: list[dict[str, Any]] = []
        for readme in sorted(self.plugins_root.glob("*/README.md")):
            plugin_dir = readme.parent
            plugin_py = plugin_dir / "plugin.py"
            if not plugin_py.exists():
                continue
            items.append(
                {
                    "name": plugin_dir.name,
                    "path": str(plugin_dir),
                    "readme": str(readme),
                }
            )
        items.sort(key=lambda item: item["name"])
        return items[:limit]

    def _render_plugin(
        self,
        slug: str,
        title: str,
        description: str,
        tool_name: str,
        category: str,
        request: str,
    ) -> str:
        return f"""from __future__ import annotations

PLUGIN_NAME = "{title}"
PLUGIN_DESCRIPTION = "{description}"


def register(registry, context):
    terminal_tools = context["terminal_tools"]
    plugin_name = "{slug}"

    def run_generated_tool(args):
        command = str(args.get("command", "")).strip()
        if not command:
            raise ValueError("A command is required.")
        timeout = int(args.get("timeout", 600))
        return terminal_tools.run_terminal(command=command, timeout=timeout)

    registry.register_tool(
        name="{tool_name}",
        description="{request}",
        input_schema={{
            "type": "object",
            "properties": {{
                "command": {{"type": "string"}},
                "timeout": {{"type": "integer", "minimum": 1, "maximum": 3600, "default": 600}},
            }},
            "required": ["command"],
            "additionalProperties": False,
        }},
        handler=run_generated_tool,
        category="{category}",
        plugin=plugin_name,
        capabilities={{"terminal"}},
    )
    return ["{tool_name}"]
"""

    def _render_readme(self, title: str, request: str, tool_name: str) -> str:
        return f"""# {title}

Generated by BOSS from the request:

> {request}

Registered tool:

- `{tool_name}`: runs a project-local terminal command through the BOSS sandbox.

Review `plugin.py` before using it in production workflows.
"""

    def _slugify(self, value: str) -> str:
        slug = re.sub(r"[^a-zA-Z0-9]+", "_", value.strip().lower()).strip("_")
        return slug or "generated"

    def _title_from_slug(self, slug: str) -> str:
        return " ".join(part.capitalize() for part in slug.replace("_plugin", "").split("_")) + " Plugin"

    def _tool_name(self, slug: str) -> str:
        base = slug.replace("_plugin", "")
        return re.sub(r"__+", "_", f"{base}_tool").strip("_")

    def _category(self, request: str) -> str:
        lowered = request.lower()
        if "docker" in lowered or "deploy" in lowered:
            return "deployment"
        if "ios" in lowered or "xcode" in lowered:
            return "ios"
        if "unreal" in lowered:
            return "game-dev"
        if "cloud" in lowered:
            return "cloud"
        return "plugin"
